In [ ]:
#Sports Score Calculator
class SportsScoreCalculator:
    def __init__(self):
        self.teams = []
        self.score = {}
        self.batsmen = {}
        self.bowler = {}
        self.current_batsmen = {}

    def get_team_names(self):
        self.teams = [input(f"Enter name for Team {i + 1}: ") for i in range(2)]
         # self.batsmen[self.teams[1]] = [input(f"Enter name of batsman {i + 1} for Team {self.teams[1]}: ") for i in range(2)]
        self.score = {team: 0 for team in self.teams}


    def display_scoreboard(self):
        print("\nCurrent Scoreboard:")
        for team, points in self.score.items():
            print(f"{team}: {points} points")

    def update_score(self, team, points, batsmen):
        if team in self.score:
            self.score[team] += points
            print(f"Updated {team}'s score by {points} points.")
        else:
            print("Team not found!")

    def reset_scoreboard(self):
        self.score = {team: 0 for team in self.teams}
        print("Scoreboard has been reset.")

    def display_final_results(self):
        print("\nFinal Results:")
        for team, points in self.score.items():
            print(f"{team}: {points} points")

    def calculate_winner(self):
        winner = max(self.score, key=self.score.get)
        print(f"\nWinner: {winner} with {self.score[winner]} points!")

    def save_match_data(self, filename):
        with open(filename, 'w') as file:
            file.write(str(self.score))
        print(f"Match data saved to {filename}.")

    def load_match_data(self, filename):
        try:
            with open(filename, 'r') as file:
                self.score = eval(file.read())
            print(f"Loaded match data from {filename}.")
        except FileNotFoundError:
            print("File not found!")

    def get_sport_type(self):
        return input("Enter the sport type (Cricket, Football, Basketball): ").lower()

class CricketScoreCalculator(SportsScoreCalculator):
    def __init__(self):
        super().__init__()
        self.wickets = {}
        self.overs = 0
        self.max_overs = 0

    def initialize_cricket_match(self):
        self.get_team_names()
        self.batsmen[self.teams[0]] = [input(f"Enter name of batsman {i + 1} for Team {self.teams[0]}: ") for i in range(2)]
        # self.batsmen[self.teams[1]] = [input(f"Enter name of batsman {i + 1} for Team {self.teams[1]}: ") for i in range(2)]
        self.bowler[self.teams[0]] = input(f"Enter name of bowler for Team {self.teams[1]}: ")
        self.wickets = {team: 0 for team in self.teams}
        self.max_overs = int(input("Enter the number of overs per side: "))
        self.overs = 0
        print(f"Match initialized for teams: {self.teams[0]} vs {self.teams[1]}. Maximum overs: {self.max_overs}.")

    def record_run(self, team):
        runs = int(input(f"Enter runs scored by {team}: "))
        if team in self.score:
            self.score[team] += runs
            print(f"Added {runs} runs to {team}.")
        else:
            print("Team not found!")

    def record_wicket(self, team):
        if team in self.wickets and self.wickets[team] < 10:  # Assuming max 10 wickets
            self.wickets[team] += 1
            print(f"Wicket taken of {team}. Total wickets now: {self.wickets[team]}")
        else:
            print("Team not found or maximum wickets reached!")

        # if team in self.wickets and self.wickets[team] < 10:  # Assuming max 10 wickets
        #     self.wickets[team] += 1
        #     self.current_batsmen = {team: list(self.batsmen[team]) for team in self.teams}
        #     if self.current_batsmen[team]:
        #       out_batsman = self.current_batsmen[team].pop(0)
        #       print(f"Wicket taken of {team}: {out_batsman}. Total wickets now: {self.wickets[team]}")
        #     else:
        #       print(f"No batsmen left for {team}!")
        # else:
        #   print("Team not found or maximum wickets reached!")


    def record_over(self):
        self.overs += 1
        print(f"Over {self.overs} completed.")
        if self.overs >= self.max_overs:
            print("Innings complete!")

    def display_cricket_scorecard(self):
        print("\nCricket Scorecard:")
        for team in self.teams:
            print(f"{team}: {self.score[team]} runs, {self.wickets[team]} wickets")

    def calculate_run_rate(self):
        if self.overs > 0:
            return sum(self.score.values()) / self.overs
        return 0

    def play_cricket_match(self):
        # Game loop for recording cricket match events
        while self.overs < self.max_overs:
            self.display_cricket_scorecard()
            for team in self.teams:
                print(f"\nPlaying over for {team}")
                self.record_run(team)
                self.record_wicket(team)

            self.record_over()

        print("\nMatch complete!")
        self.display_cricket_scorecard()
        self.calculate_winner()


class FootballScoreCalculator(SportsScoreCalculator):
    def __init__(self):
        super().__init__()
        self.time = 0
        self.yellow_cards = {team: [] for team in self.teams}
        self.red_cards = {team: [] for team in self.teams}
        self.total_game_time = 90  # Default game time in minutes

    def initialize_football_match(self):
        self.get_team_names()
        self.time = 0
        self.total_game_time = int(input("Enter the total game time in minutes (default is 90): "))
        print(f"Football match initialized between {self.teams[0]} and {self.teams[1]} for {self.total_game_time} minutes.")

    def record_goal(self, team):
        self.update_score(team, 1)
        print(f"Goal recorded for {team}!")

    def record_foul(self, team):
        print(f"Foul recorded for {team}.")

    def record_yellow_card(self, team, player):
        if team in self.teams:
            self.yellow_cards[team].append(player)
            print(f"Yellow card issued to {player} of {team}.")

    def record_red_card(self, team, player):
        if team in self.teams:
            self.red_cards[team].append(player)
            print(f"Red card issued to {player} of {team}.")

    def display_football_scoreboard(self):
        print("\nFootball Scoreboard:")
        self.display_scoreboard()
        print(f"Game Time: {self.time} minutes")
        print("\nYellow Cards:")
        for team, players in self.yellow_cards.items():
            print(f"{team}: {', '.join(players) if players else 'None'}")
        print("\nRed Cards:")
        for team, players in self.red_cards.items():
            print(f"{team}: {', '.join(players) if players else 'None'}")

    def manage_substitution(self, team, player_out, player_in):
        print(f"Substitution for {team}: {player_out} OUT, {player_in} IN.")

    def update_game_time(self, minutes):
        self.time += minutes
        if self.time >= self.total_game_time:
            self.time = self.total_game_time
            print("\nFull-time! The match is over.")
        else:
            print(f"Game time updated: {self.time} minutes.")
    def play_football_match(self):
        while self.time < self.total_game_time:
            print("\n--- Football Match Menu ---")
            print("1. Record Goal")
            print("2. Record Foul")
            print("3. Record Yellow Card")
            print("4. Record Red Card")
            print("5. Display Scoreboard")
            print("6. Manage Substitution")
            print("7. Update Game Time")
            print("8. End Match")

            choice = input("Enter your choice: ")

            if choice == '1':
                team = input(f"Enter the team name ({self.teams[0]}/{self.teams[1]}): ")
                self.record_goal(team)
            elif choice == '2':
                team = input(f"Enter the team name ({self.teams[0]}/{self.teams[1]}): ")
                self.record_foul(team)
            elif choice == '3':
                team = input(f"Enter the team name ({self.teams[0]}/{self.teams[1]}): ")
                player = input("Enter the player's name who received the yellow card: ")
                self.record_yellow_card(team, player)
            elif choice == '4':
                team = input(f"Enter the team name ({self.teams[0]}/{self.teams[1]}): ")
                player = input("Enter the player's name who received the red card: ")
                self.record_red_card(team, player)
            elif choice == '5':
                self.display_football_scoreboard()
            elif choice == '6':
                team = input(f"Enter the team name ({self.teams[0]}/{self.teams[1]}): ")
                player_out = input("Enter the player's name who is coming out: ")
                player_in = input("Enter the player's name who is coming in: ")
                self.manage_substitution(team, player_out, player_in)
            elif choice == '7':
                minutes = int(input("Enter the minutes to add to the game time: "))
                self.update_game_time(minutes)
            elif choice == '8':
                print("\nEnding the match.")
                break
            else:
                print("Invalid choice! Please try again.")

        print("\nFinal Scoreboard:")
        self.display_football_scoreboard()
        self.calculate_winner()

class BasketballScoreCalculator(SportsScoreCalculator):
    def __init__(self):
        super().__init__()
        self.period = 1

    def initialize_basketball_game(self):
        self.get_team_names()

    def record_free_throw(self, team):
        self.update_score(team, 1)

    def record_field_goal(self, team):
        self.update_score(team, 2)

    def record_three_pointer(self, team):
        self.update_score(team, 3)

    def display_basketball_scoreboard(self):
        print("\nBasketball Scoreboard:")
        self.display_scoreboard()
        print(f"Period: {self.period}")

    def calculate_field_goal_percentage(self, shots_made, shots_attempted):
        if shots_attempted > 0:
            percentage = (shots_made / shots_attempted) * 100
            print(f"Field Goal Percentage: {percentage:.2f}%")
        else:
            print("No shots attempted.")

def main_menu():
    print("Welcome to the Sports Score Calculator!")
    sport_type = input("Select sport type (Cricket, Football, Basketball): ").lower()

    if sport_type == 'cricket':
        cricket_game = CricketScoreCalculator()
        cricket_game.initialize_cricket_match()
        cricket_game_menu(cricket_game)
    elif sport_type == 'football':
        football_game = FootballScoreCalculator()
        football_game.initialize_football_match()
        football_game.play_football_match()
        # Implement a game loop or menu for football-specific actions
    elif sport_type == 'basketball':
        basketball_game = BasketballScoreCalculator()
        basketball_game.initialize_basketball_game()
        main_basketball(basketball_game)

    else:
        print("Invalid sport type!")

def cricket_game_menu(cricket_game):
    while True:
        print("\nCricket Game Menu:")
        print("1. Record Runs")
        print("2. Record Wicket")
        print("3. Complete Over")
        print("4. Display Scorecard")
        print("5. Display Run Rate")
        print("6. End Innings")
        print("7. Display Final Results")

        print("0. Exit to Main Menu")

        choice = input("Enter your choice: ")

        if choice == '1':
            team = input(f"Enter team name ({cricket_game.teams[0]} or {cricket_game.teams[1]}): ")
            cricket_game.record_run(team)
        elif choice == '2':
            team = input(f"Enter team name ({cricket_game.teams[0]} or {cricket_game.teams[1]}): ")
            cricket_game.record_wicket(team)
        elif choice == '3':
            cricket_game.record_over()
            if cricket_game.overs >= cricket_game.max_overs:
                print("Maximum overs reached!")
        elif choice == '4':
            cricket_game.display_cricket_scorecard()
        elif choice == '5':
            run_rate = cricket_game.calculate_run_rate()
            print(f"Current Run Rate: {run_rate:.2f} runs per over")
        elif choice == '6':
            print("Ending innings...")
            other_team = cricket_game.teams[1] if cricket_game.teams[0] in cricket_game.batsmen else cricket_game.teams[0]
            cricket_game.batsmen[other_team] = [input(f"Enter name of batsman {i + 1} for Team {other_team}: ") for i in range(2)]
            print(f"{other_team}'s batsmen are ready. Starting their innings!")
            cricket_game_menu(cricket_game)
            # cricket_game.record_run(other_team)
            break
        elif choice == '7' :
            cricket_game.display_final_results()
            cricket_game.calculate_winner()
        elif choice == '0':
            print("Exiting to main menu...")
            break
        else:
            print("Invalid choice! Please try again.")

def main_basketball(basketball_game):
    print("Welcome to the Basketball Score Calculator!")

    basketball_game = BasketballScoreCalculator()

    basketball_game.initialize_basketball_game()

    while True:
        print("\n--- Basketball Game Menu ---")
        print("1. Record Free Throw")
        print("2. Record Field Goal")
        print("3. Record Three Pointer")
        print("4. Display Scoreboard")
        print("5. Calculate Field Goal Percentage")
        print("6. End Game")

        choice = input("Enter your choice: ")

        if choice == '1':
            team = input(f"Enter the team name ({basketball_game.teams[0]}/{basketball_game.teams[1]}): ")
            basketball_game.record_free_throw(team)
        elif choice == '2':
            team = input(f"Enter the team name ({basketball_game.teams[0]}/{basketball_game.teams[1]}): ")
            basketball_game.record_field_goal(team)
        elif choice == '3':
            team = input(f"Enter the team name ({basketball_game.teams[0]}/{basketball_game.teams[1]}): ")
            basketball_game.record_three_pointer(team)
        elif choice == '4':
            basketball_game.display_basketball_scoreboard()
        elif choice == '5':
            shots_made = int(input("Enter the number of shots made: "))
            shots_attempted = int(input("Enter the number of shots attempted: "))
            basketball_game.calculate_field_goal_percentage(shots_made, shots_attempted)
        elif choice == '6':
            print("\nEnding the game.")
            basketball_game.display_basketball_scoreboard()
            basketball_game.calculate_winner()
            break
        else:
            print("Invalid choice! Please try again.")



main_menu()


Welcome to the Sports Score Calculator!
Select sport type (Cricket, Football, Basketball): Cricket
Enter name for Team 1: pak
Enter name for Team 2: zim
Enter name of batsman 1 for Team pak: babar
Enter name of batsman 2 for Team pak: rizwan
Enter name of bowler for Team zim: willo
Enter the number of overs per side: 1
Match initialized for teams: pak vs zim. Maximum overs: 1.

Cricket Game Menu:
1. Record Runs
2. Record Wicket
3. Complete Over
4. Display Scorecard
5. Display Run Rate
6. End Innings
7. Display Final Results
0. Exit to Main Menu
Enter your choice: 1
Enter team name (pak or zim): pak
Enter runs scored by pak: 45
Added 45 runs to pak.

Cricket Game Menu:
1. Record Runs
2. Record Wicket
3. Complete Over
4. Display Scorecard
5. Display Run Rate
6. End Innings
7. Display Final Results
0. Exit to Main Menu
Enter your choice: 2
Enter team name (pak or zim): pak
Wicket taken of pak. Total wickets now: 1

Cricket Game Menu:
1. Record Runs
2. Record Wicket
3. Complete Over
4. Dis

In [ ]:
import tkinter as tk
from tkinter import messagebox

class CricketScoreCalculator:
    def __init__(self):
        self.teams = []
        self.score = {}
        self.wickets = {}
        self.overs = 0
        self.max_overs = 0
        self.current_innings = 1

    def initialize_match(self, team1, team2, max_overs):
        self.teams = [team1, team2]
        self.score = {team: 0 for team in self.teams}
        self.wickets = {team: 0 for team in self.teams}
        self.max_overs = int(max_overs)
        self.overs = 0
        return f"Match initialized: {team1} vs {team2}, {max_overs} overs per innings."

    def record_run(self, team, runs):
        if team in self.score:
            self.score[team] += int(runs)
            return f"Added {runs} runs to {team}. Total: {self.score[team]} runs."
        return "Team not found!"

    def record_wicket(self, team):
        if team in self.wickets and self.wickets[team] < 10:  # Max 10 wickets
            self.wickets[team] += 1
            return f"Wicket for {team}. Total wickets: {self.wickets[team]}"
        return "Team not found or maximum wickets reached!"

    def next_over(self):
        self.overs += 1
        if self.overs >= self.max_overs:
            return "Innings complete!"
        return f"Over {self.overs} completed."

    def display_scorecard(self):
        scorecard = "Scorecard:\n"
        for team in self.teams:
            scorecard += f"{team}: {self.score[team]} runs, {self.wickets[team]} wickets\n"
        return scorecard

    def calculate_winner(self):
        winner = max(self.score, key=self.score.get)
        return f"Winner: {winner} with {self.score[winner]} runs!"

# GUI Class
class CricketScoreCalculatorGUI:
    def __init__(self, root):
        self.calculator = CricketScoreCalculator()
        self.root = root
        self.root.title("Cricket Score Calculator")

        # Match Initialization
        tk.Label(root, text="Team 1 Name:").grid(row=0, column=0)
        self.team1_entry = tk.Entry(root)
        self.team1_entry.grid(row=0, column=1)

        tk.Label(root, text="Team 2 Name:").grid(row=1, column=0)
        self.team2_entry = tk.Entry(root)
        self.team2_entry.grid(row=1, column=1)

        tk.Label(root, text="Overs per Innings:").grid(row=2, column=0)
        self.overs_entry = tk.Entry(root)
        self.overs_entry.grid(row=2, column=1)

        self.init_button = tk.Button(root, text="Initialize Match", command=self.initialize_match)
        self.init_button.grid(row=3, column=0, columnspan=2)

        # Match Actions
        tk.Label(root, text="Team:").grid(row=4, column=0)
        self.team_select = tk.StringVar(root)
        self.team_menu = tk.OptionMenu(root, self.team_select, "")
        self.team_menu.grid(row=4, column=1)

        tk.Label(root, text="Runs:").grid(row=5, column=0)
        self.runs_entry = tk.Entry(root)
        self.runs_entry.grid(row=5, column=1)

        self.add_runs_button = tk.Button(root, text="Add Runs", command=self.add_runs)
        self.add_runs_button.grid(row=6, column=0)

        self.add_wicket_button = tk.Button(root, text="Add Wicket", command=self.add_wicket)
        self.add_wicket_button.grid(row=6, column=1)

        self.next_over_button = tk.Button(root, text="Next Over", command=self.next_over)
        self.next_over_button.grid(row=7, column=0, columnspan=2)

        self.scorecard_button = tk.Button(root, text="Show Scorecard", command=self.show_scorecard)
        self.scorecard_button.grid(row=8, column=0, columnspan=2)

        self.winner_button = tk.Button(root, text="Calculate Winner", command=self.show_winner)
        self.winner_button.grid(row=9, column=0, columnspan=2)

    def initialize_match(self):
        team1 = self.team1_entry.get()
        team2 = self.team2_entry.get()
        overs = self.overs_entry.get()

        if team1 and team2 and overs.isdigit():
            message = self.calculator.initialize_match(team1, team2, overs)
            self.update_team_menu()
            messagebox.showinfo("Match Initialized", message)
        else:
            messagebox.showerror("Error", "Please enter valid team names and overs.")

    def update_team_menu(self):
        menu = self.team_menu["menu"]
        menu.delete(0, "end")
        for team in self.calculator.teams:
            menu.add_command(label=team, command=lambda t=team: self.team_select.set(t))
        self.team_select.set(self.calculator.teams[0] if self.calculator.teams else "")

    def add_runs(self):
        team = self.team_select.get()
        runs = self.runs_entry.get()
        if team and runs.isdigit():
            message = self.calculator.record_run(team, runs)
            messagebox.showinfo("Runs Added", message)
        else:
            messagebox.showerror("Error", "Select a team and enter valid runs.")

    def add_wicket(self):
        team = self.team_select.get()
        if team:
            message = self.calculator.record_wicket(team)
            messagebox.showinfo("Wicket Added", message)
        else:
            messagebox.showerror("Error", "Select a team to add a wicket.")

    def next_over(self):
        message = self.calculator.next_over()
        messagebox.showinfo("Over Completed", message)

    def show_scorecard(self):
        scorecard = self.calculator.display_scorecard()
        messagebox.showinfo("Scorecard", scorecard)

    def show_winner(self):
        winner = self.calculator.calculate_winner()
        messagebox.showinfo("Match Winner", winner)

# Run the GUI
if __name__ == "__main__":
    root = tk.Tk()
    app = CricketScoreCalculatorGUI(root)
    root.mainloop()


TclError: no display name and no $DISPLAY environment variable

In [ ]:
import tkinter as tk
from tkinter import messagebox

class CricketScoreCalculator:
    # ... (Existing CricketScoreCalculator class code) ...

  class CricketScoreCalculatorGUI:
    def __init__(self, root):
        self.calculator = CricketScoreCalculator()
        self.root = root
        self.root.title("Cricket Score Calculator")

        # Match Initialization
        tk.Label(root, text="Team 1 Name:").grid(row=0, column=0)
        self.team1_entry = tk.Entry(root)
        self.team1_entry.grid(row=0, column=1)

        tk.Label(root, text="Team 2 Name:").grid(row=1, column=0)
        self.team2_entry = tk.Entry(root)
        self.team2_entry.grid(row=1, column=1)

        tk.Label(root, text="Overs per Innings:").grid(row=2, column=0)
        self.overs_entry = tk.Entry(root)
        self.overs_entry.grid(row=2, column=1)

        self.init_button = tk.Button(root, text="Initialize Match", command=self.initialize_match)
        self.init_button.grid(row=3, column=0, columnspan=2)

        # Match Actions
        tk.Label(root, text="Team:").grid(row=4, column=0)
        self.team_select = tk.StringVar(root)
        self.team_menu = tk.OptionMenu(root, self.team_select, "")  # Initially empty
        self.team_menu.grid(row=4, column=1)

        tk.Label(root, text="Runs:").grid(row=5, column=0)
        self.runs_entry = tk.Entry(root)
        self.runs_entry.grid(row=5, column=1)

        self.add_runs_button = tk.Button(root, text="Add Runs", command=self.add_runs)
        self.add_runs_button.grid(row=6, column=0)

        self.add_wicket_button = tk.Button(root, text="Add Wicket", command=self.add_wicket)
        self.add_wicket_button.grid(row=6, column=1)

        self.next_over_button = tk.Button(root, text="Next Over", command=self.next_over)
        self.next_over_button.grid(row=7, column=0, columnspan=2)

        self.scorecard_button = tk.Button(root, text="Show Scorecard", command=self.show_scorecard)
        self.scorecard_button.grid(row=8, column=0, columnspan=2)

        self.winner_button = tk.Button(root, text="Calculate Winner", command=self.show_winner)
        self.winner_button.grid(row=9, column=0, columnspan=2)

    # ... (Rest of the CricketScoreCalculatorGUI methods) ...

# Run the GUI
if __name__ == "__main__":
    # root = tk.Tk()
    # app = CricketScoreCalculatorGUI(root)
    # root.mainloop()
    root = tk.Tk()
    tk.Label(root, text="Hello, tkinter!").pack()
    root.mainloop()

TclError: no display name and no $DISPLAY environment variable

In [ ]:
# # List of lists
import pandas as pd
# data = [
#     ['Alice', 25, 'New York'],
#     ['Bob', 30, 'Los Angeles'],
#     ['Charlie', 35, 'Chicago']
# ]

# # Column names
# columns = ['Name', 'Age', 'City']

# # Create DataFrame
# df = pd.DataFrame(data, columns=columns)

# print(df)
import numpy as np

# Create a NumPy array
data = np.array([
    ['Alice', 25, 'New York'],
    ['Bob', 30, 'Los Angeles'],
    ['Charlie', 35, 'Chicago']
])

# Create DataFrame
df = pd.DataFrame(data, columns=['Name', 'Age', 'City'])

print(df)



      Name Age         City
0    Alice  25     New York
1      Bob  30  Los Angeles
2  Charlie  35      Chicago


In [ ]:
import numpy as np

# Example sales data for 4 products over 6 weeks
sales_data = np.array([
    [120, 230, 310, 450],  # Week 1
    [115, 245, 320, 460],  # Week 2
    [130, 220, 300, 470],  # Week 3
    [140, 210, 290, 480],  # Week 4
    [125, 235, 280, 490],  # Week 5
    [135, 240, 270, 500]   # Week 6
])

# 1. Dimensions and Size of Each Element
print("Dimensions of the array:", sales_data.shape)  # (6, 4)
print("Size of each element (in bytes):", sales_data.itemsize)  # Size of a single element

# 2. Reshape the array (if necessary)
# It is already 6 rows and 4 columns, but if not:
reshaped_data = sales_data.reshape(6, 4)
print("\nReshaped Array:\n", reshaped_data)

# 3. Extract sales data for weeks 3 to 5 for the first two products
extracted_data = sales_data[2:5, 0:2]
print("\nSales data for weeks 3 to 5 (first two products):\n", extracted_data)

# 4. Sort sales data for the third product in ascending order
third_product_sales = sales_data[:, 2]  # Extract data for the third product
sorted_third_product_sales = np.sort(third_product_sales)
print("\nSorted sales data for the third product:\n", sorted_third_product_sales)


Dimensions of the array: (6, 4)
Size of each element (in bytes): 8

Reshaped Array:
 [[120 230 310 450]
 [115 245 320 460]
 [130 220 300 470]
 [140 210 290 480]
 [125 235 280 490]
 [135 240 270 500]]

Sales data for weeks 3 to 5 (first two products):
 [[130 220]
 [140 210]
 [125 235]]

Sorted sales data for the third product:
 [270 280 290 300 310 320]
